#!/bin/sh

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

echo "Early unbind pci ports" > /dev/kmsg

if [ -f /etc/unbindpci.conf ]; then
         echo "Unbinding pci ports..." > /dev/kmsg
         IFS=,
         while read addr driver; do
         if [ -f /sys/bus/pci/drivers/$driver/unbind ]; then
               echo "Unbinding $addr, device $driver" > /dev/kmsg
               echo $addr > /sys/bus/pci/drivers/$driver/unbind
         fi
         done < /etc/unbindpci.conf
fi
